apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricreader
  labels:
    app: metricreader
spec:
  selector:
    matchLabels:
      app: metricreader
  template:
    metadata:
      labels:
        app: metricreader
    spec:
      containers:
        - name: metricreader
          image: localhost:32000/metricreader:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: API_URL
              value: http://10.1.124.197:9090
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
